### ISSUE TITLE
FYI - chrome extension released which blocks ip leaks

### ISSUE THREAD

**Issue by gavin20** [diafygi/webrtc-ips#12]
A VPN provider released their own Chrome extension which now blocks webrtc leaks. Not sure how easy to circumvent though.

[Extension](https://chrome.google.com/webstore/detail/webrtc-stopper/mfehokchlmjlkmlgjhkmlpcldcbcooec?utm_source=chrome-app-launcher-info-dialog)

Confirmed blocking in demos [here](http://146.148.121.175:8080/webrtc-ips/) & [here](https://diafygi.github.io/webrtc-ips/).

**Comment by upsuper** [comment]
Don't worry, it has been bypassed, as I commented in the review.

**Comment by diafygi** [comment]
Updated to bypass this extension.

**Comment by sepehr** [comment]
Huh, thank you @upsuper.
