### ISSUE TITLE
Got "ICE failed" on your demo page

### ISSUE THREAD

**Issue by ghost** [diafygi/webrtc-ips#19]
Hi.
I got critical error "ICE failed, see about:webrtc for more details" on your script, even on your demo page.
I have Windows 7, Firefox 39.

**Comment by diafygi** [comment]
@psyhonut can you please post a screenshot with the console open? I do not have access to a windows machine to try and reproduce. It works fine on Linux, Firefox 39.

**Comment by ghost** [comment]
![1](https://cloud.githubusercontent.com/assets/1383457/8926575/7440ef94-3519-11e5-8d73-6ad5e45861ee.PNG)

**Comment by diafygi** [comment]
Do you have webrtc enabled? What is your media.peerconnection.enabled setting in about:config?

**Comment by diafygi** [comment]
Closing due to no response for several months.
