### ISSUE TITLE
Update Demo Page - Include Note About WebRTC Leak Prevent

### ISSUE THREAD

**Issue by war59312** [diafygi/webrtc-ips#20]
Hi,

On the Demo Page @ https://diafygi.github.io/webrtc-ips/

"These requests do not show up in developer consoles and cannot be blocked by browser plugins (AdBlock, Ghostery, etc.)."

That's not really true anymore. The and part. ;)

WebRTC Leak Prevent: https://chrome.google.com/webstore/detail/webrtc-leak-prevent/eiadekoaikejlgdbkbdfeijglgfdalml?utm_source=chrome-app-launcher-info-dialog

Perhaps add a note about it.

Thanks,

Will

**Comment by diafygi** [comment]
The extension you linked to does not block all STUN requests, it only limits the STUN request to the default route. This default STUN request still cannot be seen/filtered/blocked by extensions in Chrome. See https://www.w3.org/wiki/Privacy/IPAddresses#Using_wildcard_DNS_entries_as_persistent_identifiers

**Comment by Naereen** [comment]
Apparently, [this Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/statutory/) does a pretty good job in blocking any WebRTC RTCPeerConnection.
As it says:
  « Prevents Private IP Information Leakage from WebRTC until the user is notified and accepts the websites access request for using WebRTC RTCPeerConnection »

If you think it really fixes the security issue, could you add a link to the addon in the demo page?
