### ISSUE TITLE
iframe is not defined

### ISSUE THREAD

**Issue by alex-kinokon** [diafygi/webrtc-ips#21]
``` javascript
var win = iframe.contentWindow;
```

should probably be

``` javascript
var win = document.getElementById('iframe').contentWindow;
```

since `iframe` is not defined.

**Comment by diafygi** [comment]
This is intentional to get around extensions that try to block WebRTC through javascript trickery.

**Comment by diafygi** [comment]
Actually, did you get an error in a browser? Which browser?

**Comment by alex-kinokon** [comment]
My bad. `iframe` is indeed defined.

**Comment by wondervendor** [comment]
In PaleMoon 25.8.1 it says "ReferenceError: iframe is not defined".
But it works fine in my Firefox 38.0.5 installed in the same OS.
