### ISSUE TITLE
Error Demo

### ISSUE THREAD

**Issue by bylinggha** [diafygi/webrtc-ips#22]
I got error in firebug like this.

Error: RTCPeerConnection constructor passed invalid RTCConfiguration - missing url

var pc = new RTCPeerConnection(servers, mediaConstraints);

**Comment by diafygi** [comment]
Can you please give some more information about what version of Firefox and firebug you are using? Do you also see the error in the built-in Firefox debugger console?

**Comment by bylinggha** [comment]
Im try to update firefox 40.0.1 to 41.0.2 and problem solved .

Thanks.,
