### ISSUE TITLE
requests blocking ... 

### ISSUE THREAD

**Issue by olexande** [diafygi/webrtc-ips#23]
You writing: "This demo secretly makes requests to STUN servers that can log your request. These requests do not show up in developer consoles and cannot be blocked by browser plugins (AdBlock, Ghostery, etc.). "

Try to check NoScript Plugin ;)

**Comment by diafygi** [comment]
NoScript doesn't block WebRTC, it blocks all javascript. What I mean is that WebRTC cannot be blocked specifically.

**Comment by olexande** [comment]
maybe...
but blocking ;)
