### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by gondo** [diafygi/webrtc-ips#3]
what about ipv6?

**Comment by diafygi** [comment]
There is no need to make a STUN request for an IPv6 address, since there is no NAT in IPv6.

**Comment by KwadroNaut** [comment]
If you use for example a dual-stack host, with a firewall blocking all IPv6 connections, you can still find out the (globally routable) IPv6 address with your code (obviously with a changed IP-regex, but that's minor). I've tested this in Chrome 43.

**Comment by diafygi** [comment]
Gotcha, will investigate a bit.

**Comment by diafygi** [comment]
Added in commit 9b890464b8c53d7fb6d11d736d940cb53c2b3856
