### ISSUE TITLE
Can't use return statement to store in variable

### ISSUE THREAD

**Issue by superwhiskers** [diafygi/webrtc-ips#32]
I can't seem to use a return statement to put it in a variable

function addIP(ip) {
  return ip
}

var ip = findIP(addIP);

doesn't return the ip

**Comment by bondt** [comment]
Are you referring to the function `function getIPs(callback){}` ? If so, use the `callback` parameter to enter a callback where the `ip` is set, like so:

``` js
// given function
function getIPs(callback) {
  var someIp = '1.2.3.4';
  callback(someIp); // 'callback' is a function
}

var myIp = '';
getIPs(function(ip) {
  myIp = ip; // sets 'myIp' to the IP passed in the callback in the given function
});
```

The reason for this, is that the process is done async. It doesn't have a return value, but rather has to wait to find something and pass it to the callback function.

Hope this helps!
