### ISSUE TITLE
Only showing local IP

### ISSUE THREAD

**Issue by maheshambiga** [diafygi/webrtc-ips#33]
The demo does not seem to display public IP and IPv4/IPv6. It only displays local IP. When I looked into the code, came across if conditions and RegEx. This will eventually end up showing one IP at a time. Not much of use. 
I am looking for a way to find users public as well as local IP.

**Comment by ghost** [comment]
Issue not resolved yet : i have the same issue on _Windows 10_ running **Google Chrome 59.0.3071.115 (Official Build) (64-bit)**

**Comment by PatSpiegel** [comment]
use another server
example: `var servers = {iceServers: [{urls: "stun:stun.l.google.com:19302?transport=udp"}]};`

**Comment by JoyChou93** [comment]
@PatSpiegel It's not ok.

**Comment by AJ-Acevedo** [comment]
Changing the server works
`var servers = {iceServers: [{urls: "stun:stun.l.google.com:19302?transport=udp"}]};`

**Comment by ashwanthkrishna** [comment]
How to run this code.cant able to get public IP address.Can anyone help me please???

**Comment by maheshambiga** [comment]
Closing this issue as majority of users have agreed it works with alternate server urls.

**Comment by maheshambiga** [comment]
Closing this issue as majority of users have agreed it works with alternative server urls
