### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by joshgillies** [diafygi/webrtc-ips#6]
Is this mitigated by using Tor? Or does WebRTC expose this information regardless?

**Comment by joshgillies** [comment]
I guess if you're one to go as far as to do your browsing through Tor you'd also use a browser that doesn't implement such features.

**Comment by diafygi** [comment]
Yes. WebRTC isn't included in the Tor browser, so this wont work when using the Tor browser bundle. It is discouraged to use another browser besides the one in the browser bundle.
