### ISSUE TITLE
plugins can block requests be blocking all javascript

### ISSUE THREAD

**Issue by neuhaus** [diafygi/webrtc-ips#9]
The demo page states:

"These requests do not show up in developer consoles and cannot be blocked by browser plugins (AdBlock, Ghostery, etc.). "

This is slightly misleading because NoScript will of course block them until JavaScript is permitted.

**Comment by diafygi** [comment]
Of course, but blocking javascript altogether isn't a viable solution for most people. Additionally, if you allow limited scripts via NoScript as is often recommended, it will still allow the STUN request to a third party domains, even if it does block requests to third party domains via ajax requests.
